# Use the latest version of the theme; GitHub serves an outdated one.
remote_theme: pages-themes/minimal
# The theme is not called "minimal"
theme_name: jekyll-theme-minimal
title: Better Code
description: STLab Better Code course

exclude:
  - materials
