version: '2'
services:
  jekyll:
    environment:
      - JEKYLL_ENV=docker
      - PAGES_REPO_NWO=stlab/better-code
    command: >
        jekyll serve --force-polling --watch --incremental
        --config _config.yml,_config.docker.yml
        --livereload
    image: jekyll/jekyll:pages
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
      - 35729:35729
